name: iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest

    steps:
      - name: iOS Build Action
        uses: yukiarrr/ios-build-action@v1.11.0
        with:
          project-path: The Notes.xcodeproj
          code-signing-identity: iOS Distribution
          team-id: 0
      
      - name: Archive and Export
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS' }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild archive -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "generic/platform=iOS" -archivePath "build/$scheme.xcarchive"
          xcodebuild -exportArchive -archivePath "build/$scheme.xcarchive" -exportOptionsPlist "ExportOptions.plist" -exportPath "build"

      - name: Save Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ runner.os }}-artifact
          path: build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.6.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: ${{ runner.os }}-artifact.ipa
          groups: developer
          releaseNotes: ${{ github.event.head_commit.message }}
          debug: true
